
import React, { useState } from 'react';
import { Share2, Download, Copy, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { downloadResultsAsCSV, copyResultsToClipboard, shareResults } from '@/utils/downloadUtils';
import { showSuccessToast } from '@/utils/notificationUtils';
import { UnitSystem } from '@/types/calculatorTypes';

interface ResultActionsProps {
  title: string;
  results: Record<string, string>;
  fileName: string;
  userName?: string;
  unitSystem: string;
}

export const ResultActions: React.FC<ResultActionsProps> = ({ 
  title, 
  results, 
  fileName,
  userName,
  unitSystem
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const resultData = {
      title,
      results,
      date: new Date().toLocaleDateString(),
      unitSystem: unitSystem as UnitSystem,
      userName: userName || undefined,
      footer: "Generated by: SurviveWellness"
    };
    
    copyResultsToClipboard(resultData);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    showSuccessToast("Results copied to clipboard");
  };

  const handleShare = () => {
    const resultData = {
      title,
      results,
      date: new Date().toLocaleDateString(),
      unitSystem: unitSystem as UnitSystem,
      userName: userName || undefined,
      footer: "Generated by: SurviveWellness"
    };
    
    shareResults(resultData);
  };

  const handleDownload = () => {
    const resultData = {
      title,
      results,
      date: new Date().toLocaleDateString(),
      unitSystem: unitSystem as UnitSystem,
      userName: userName || undefined,
      footer: "Generated by: SurviveWellness\nFor more calculators visit: https://survivewellness.com/tools-calculators/"
    };
    
    downloadResultsAsCSV(resultData, fileName);
    showSuccessToast("Results downloaded successfully!");
  };

  return (
    <div className="mt-4">
      <div className="flex flex-wrap gap-2">
        <button onClick={handleCopy} className="action-button action-button-primary">
          <Copy className="h-4 w-4" />
          {copied ? "Copied!" : "Copy"}
        </button>
        <button onClick={handleShare} className="action-button action-button-primary">
          <Share2 className="h-4 w-4" />
          Share
        </button>
        <button onClick={handleDownload} className="action-button action-button-primary">
          <Download className="h-4 w-4" />
          Download
        </button>
      </div>
      
      <div className="mt-4 pt-4 border-t border-dashed border-gray-200 dark:border-gray-700 text-xs text-gray-500 dark:text-gray-400">
        <p><strong>Generated by:</strong> SurviveWellness</p>
        <p className="mt-1 flex items-center">
          <span>For more calculators visit:</span>
          <a 
            href="https://survivewellness.com/tools-calculators/" 
            target="_blank" 
            rel="noopener noreferrer"
            className="ml-1 text-wellness-blue flex items-center hover:underline"
          >
            SurviveWellness Calculators
            <ExternalLink className="h-3 w-3 ml-0.5" />
          </a>
        </p>
      </div>
    </div>
  );
};

export default ResultActions;
